# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmessage.proto\"!\n\x05Point\x12\x0b\n\x03lat\x18\x01 \x01(\x01\x12\x0b\n\x03lng\x18\x02 \x01(\x01\"\x8c\x01\n\x05Route\x12\x0c\n\x04name\x18\x01 \x01(\x04\x12\x19\n\twaypoints\x18\x02 \x03(\x0b\x32\x06.Point\x12\r\n\x05\x63olor\x18\x03 \x01(\t\x12\x11\n\tspeed_avg\x18\x04 \x01(\r\x12\x13\n\x0bspeed_stdev\x18\x05 \x01(\r\x12\x0f\n\x07reverse\x18\x06 \x01(\x08\x12\x12\n\nnext_point\x18\x07 \x01(\r\"$\n\x02Ue\x12\x0c\n\x04imsi\x18\x01 \x01(\x04\x12\x10\n\x08rotation\x18\x05 \x01(\r\"7\n\x11UePositionRequest\x12\x14\n\x0cprocess_code\x18\x01 \x01(\x04\x12\x0c\n\x04imsi\x18\x02 \x03(\x04\"6\n\x0fUePositionReply\x12\x0c\n\x04imsi\x18\x01 \x01(\x04\x12\x15\n\x05point\x18\x02 \x01(\x0b\x32\x06.Point27\n\x03Ues\x12\x30\n\x06GetUes\x12\x12.UePositionRequest\x1a\x10.UePositionReply0\x01\x62\x06proto3')



_POINT = DESCRIPTOR.message_types_by_name['Point']
_ROUTE = DESCRIPTOR.message_types_by_name['Route']
_UE = DESCRIPTOR.message_types_by_name['Ue']
_UEPOSITIONREQUEST = DESCRIPTOR.message_types_by_name['UePositionRequest']
_UEPOSITIONREPLY = DESCRIPTOR.message_types_by_name['UePositionReply']
Point = _reflection.GeneratedProtocolMessageType('Point', (_message.Message,), {
  'DESCRIPTOR' : _POINT,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:Point)
  })
_sym_db.RegisterMessage(Point)

Route = _reflection.GeneratedProtocolMessageType('Route', (_message.Message,), {
  'DESCRIPTOR' : _ROUTE,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:Route)
  })
_sym_db.RegisterMessage(Route)

Ue = _reflection.GeneratedProtocolMessageType('Ue', (_message.Message,), {
  'DESCRIPTOR' : _UE,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:Ue)
  })
_sym_db.RegisterMessage(Ue)

UePositionRequest = _reflection.GeneratedProtocolMessageType('UePositionRequest', (_message.Message,), {
  'DESCRIPTOR' : _UEPOSITIONREQUEST,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:UePositionRequest)
  })
_sym_db.RegisterMessage(UePositionRequest)

UePositionReply = _reflection.GeneratedProtocolMessageType('UePositionReply', (_message.Message,), {
  'DESCRIPTOR' : _UEPOSITIONREPLY,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:UePositionReply)
  })
_sym_db.RegisterMessage(UePositionReply)

_UES = DESCRIPTOR.services_by_name['Ues']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _POINT._serialized_start=17
  _POINT._serialized_end=50
  _ROUTE._serialized_start=53
  _ROUTE._serialized_end=193
  _UE._serialized_start=195
  _UE._serialized_end=231
  _UEPOSITIONREQUEST._serialized_start=233
  _UEPOSITIONREQUEST._serialized_end=288
  _UEPOSITIONREPLY._serialized_start=290
  _UEPOSITIONREPLY._serialized_end=344
  _UES._serialized_start=346
  _UES._serialized_end=401
# @@protoc_insertion_point(module_scope)
