# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import msg_pb2 as msg__pb2


class UEsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetUEs = channel.unary_stream(
                '/msg.UEs/GetUEs',
                request_serializer=msg__pb2.UERequest.SerializeToString,
                response_deserializer=msg__pb2.UEInfo.FromString,
                )


class UEsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetUEs(self, request, context):
        """rpc CreateUser (users.CreateUserRequest) returns (users.CreateUserResult);
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UEsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetUEs': grpc.unary_stream_rpc_method_handler(
                    servicer.GetUEs,
                    request_deserializer=msg__pb2.UERequest.FromString,
                    response_serializer=msg__pb2.UEInfo.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'msg.UEs', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class UEs(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetUEs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/msg.UEs/GetUEs',
            msg__pb2.UERequest.SerializeToString,
            msg__pb2.UEInfo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
