# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tmsg.proto\x12\x03msg\"$\n\x08Location\x12\x0b\n\x03Lat\x18\x01 \x01(\x01\x12\x0b\n\x03Lng\x18\x02 \x01(\x01\"D\n\x06UEInfo\x12\x0c\n\x04Imsi\x18\x01 \x01(\x04\x12\x1b\n\x04Loca\x18\x02 \x01(\x0b\x32\r.msg.Location\x12\x0f\n\x07\x62\x65\x61ring\x18\x03 \x01(\x01\"*\n\x0bUEInfoArray\x12\x1b\n\x06uEInfo\x18\x01 \x03(\x0b\x32\x0b.msg.UEInfo\"\"\n\tUERequest\x12\x15\n\rprocesureCode\x18\x01 \x01(\x04\x32.\n\x03UEs\x12\'\n\x06GetUEs\x12\x0e.msg.UERequest\x1a\x0b.msg.UEInfo0\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'msg_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LOCATION._serialized_start=18
  _LOCATION._serialized_end=54
  _UEINFO._serialized_start=56
  _UEINFO._serialized_end=124
  _UEINFOARRAY._serialized_start=126
  _UEINFOARRAY._serialized_end=168
  _UEREQUEST._serialized_start=170
  _UEREQUEST._serialized_end=204
  _UES._serialized_start=206
  _UES._serialized_end=252
# @@protoc_insertion_point(module_scope)
