# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import message_pb2 as message__pb2


class UesStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetUes = channel.unary_stream(
                '/Ues/GetUes',
                request_serializer=message__pb2.UePositionRequest.SerializeToString,
                response_deserializer=message__pb2.UePositionReply.FromString,
                )


class UesServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetUes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetUes': grpc.unary_stream_rpc_method_handler(
                    servicer.GetUes,
                    request_deserializer=message__pb2.UePositionRequest.FromString,
                    response_serializer=message__pb2.UePositionReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Ues', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Ues(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetUes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/Ues/GetUes',
            message__pb2.UePositionRequest.SerializeToString,
            message__pb2.UePositionReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
